### ISSUE TITLE
JOSS Review: @elimillera

### ISSUE THREAD

**Issue by elimillera** [jackmwolf/tehtuner#14]
Hey @jackmwolf, I've completed my review of the package. Overall a very good functioning and documented package. Below I've noted a couple small improvements. 

- Automated tests
In the tests/testhat directory there is only a single test which is testing for the lack of an error. Consider making the tests more robust and adding tests for equality with `expect_equal` to verify the output is as expected and correct.

- Community guidelines
Consider adding a CONTRIBUTING.md to the root of the repository to clarify how people can contribute to the project. An example can be found [here](https://contributing.md/example/).

- State of the field
I've done a brief search for similar packages and I found [hdcate](https://cran.r-project.org/web/packages/hdcate/) which looks to have a similar purpose. Consider adding this to the state of the field section.

https://github.com/openjournals/joss-reviews/issues/5453

**Comment by jackmwolf** [comment]
Hi @elimillera! Thank you for the suggestions- I have worked to address them all:

1. I have added automated tests for all of the internal Step 1 wrapper functions (e.g., `vt1_lasso`) to verify their predictions agree with Step 1 models manually fit by hand. I have also added a test to confirm that the proposed minimum null penalty parameter returned from `get_mnpp` results in a null Step 2 model for all possible Step 2 models. These tests live in [`test-main.R`](https://github.com/jackmwolf/tehtuner/blob/9f481459721ab8d71f4bbdc8bc63dc447ae43dfa/tests/testthat/test-main.R) (commit 9f48145).
2. I have modified the example you provided for this project and placed it in the root [`CONTRIBUTING.md`](https://github.com/jackmwolf/tehtuner/blob/9f481459721ab8d71f4bbdc8bc63dc447ae43dfa/CONTRIBUTING.md) (commit 9f48145).
3. Thank you for bringing `hdcate` to my attention. I have cited it in the state of the field as an alternative method for analyzing the conditional average treatment effect and noted how it is different from the Virtual Twins approach implemented in `tehtuner` (commits c2c16d4 and e71c2b7 in [branch 12-write-an-article-for-the-journal-of-open-source-software](https://github.com/jackmwolf/tehtuner/tree/12-write-an-article-for-the-journal-of-open-source-software)). I have verified that the paper renders a PDF without errors after these changes.

Please let me know if you have any further questions. Again, thank you for the feedback and help to improve the package.

**Comment by elimillera** [comment]
Looks great. Thanks @jackmwolf
